close all hidden
clear all

%mycolors

rng(0)

height = 2/3;
set(0,...
'defaultfigureposition',[200 400 800 800*height],...
'defaultaxeslinewidth',1,...
'defaultaxesfontsize',16,...
'defaultlinelinewidth',2,...
'defaultpatchlinewidth',1,...
'defaultlinemarkersize',10,...
'defaulttextinterpreter','tex');